apiVersion: apps/v1
kind: Deployment
metadata:
  name: friends
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: friends
        env:
        - name: MONGODB_URI
          value: "mongodb://admin:password@mongodb:27017"
        - name: LOG_LEVEL
          value: "debug"
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "100m"