apiVersion: v1
kind: Service
metadata:
  name: matching
  labels:
    app: matching
spec:
  selector:
    app: matching
  ports:
    - protocol: TCP
      port: 50052
      targetPort: 50052
  type: ClusterIP