apiVersion: v1
kind: Service
metadata:
  name: friends
  labels:
    app: friends
spec:
  selector:
    app: friends
  ports:
    - protocol: TCP
      port: 50056
      targetPort: 50056
  type: ClusterIP