apiVersion: v1
kind: Service
metadata:
  name: leaderboard
  labels:
    app: leaderboard
spec:
  selector:
    app: leaderboard
  ports:
    - protocol: TCP
      port: 50054
      targetPort: 50054
  type: ClusterIP